//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Linq.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusiUnit
    {
        public int BusiUnitId { get; set; }
        public int BusiUnitTypeID { get; set; }
        public string RegionCode { get; set; }
        public string BusiUnitCode { get; set; }
        public string ERPCode { get; set; }
        public string BusiUnitName { get; set; }
        public string ShortName { get; set; }
        public string HelperCode { get; set; }
        public Nullable<int> OrderId { get; set; }
        public string Address { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string WebSiteUrl { get; set; }
        public string FtpSiteUrl { get; set; }
        public string Telephone1 { get; set; }
        public string Telephone2 { get; set; }
        public string Fax { get; set; }
        public string E_Mail { get; set; }
        public Nullable<decimal> X { get; set; }
        public Nullable<decimal> Y { get; set; }
        public bool Status { get; set; }
        public string Remark { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string FMISCode { get; set; }
        public string BosCode { get; set; }
        public string ERPCode_Company { get; set; }
        public string ERPCode_Profit { get; set; }
        public string ERPCode_Client { get; set; }
        public string FMISCode_Duty { get; set; }
        public string FMISCode_Cost { get; set; }
        public string FMISCode_Client { get; set; }
    }
}
