//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Linq.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepotPerson
    {
        public int PersonID { get; set; }
        public string PersonCode { get; set; }
        public string WorkNo { get; set; }
        public string PersonName { get; set; }
        public string DomainAcc { get; set; }
        public string PassWord { get; set; }
        public Nullable<int> SexId { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string IDCard { get; set; }
        public byte[] Photo { get; set; }
        public string Nation { get; set; }
        public string NativePlace { get; set; }
        public Nullable<int> PoliticalId { get; set; }
        public Nullable<System.DateTime> JoinDate { get; set; }
        public Nullable<int> EducationId { get; set; }
        public string GraduateFrom { get; set; }
        public string Perfessional { get; set; }
        public string Ability { get; set; }
        public Nullable<bool> IsFulltime { get; set; }
        public string HomeAddress { get; set; }
        public string PostCode { get; set; }
        public Nullable<int> WorkType { get; set; }
        public Nullable<System.DateTime> WorkStartDate { get; set; }
        public Nullable<int> JobLevel { get; set; }
        public Nullable<System.DateTime> JobSure { get; set; }
        public Nullable<int> DutyId { get; set; }
        public Nullable<System.DateTime> DutySure { get; set; }
        public string Contact { get; set; }
        public string Officephone { get; set; }
        public string Homephone { get; set; }
        public string Mobilephone { get; set; }
        public string EMail { get; set; }
        public string Certificate { get; set; }
        public bool Status { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public string Remark { get; set; }
        public string HelperCode { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
